baseURL = "http://example.org/"
languageCode = "en-us"
title = "Foxtrot"
theme = "foxtrot-theme"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
tags = ["tags"]